routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
*/


use Illuminate\Support\Facades\Auth;


  
// Route::group(['middleware' => ['auth', 'revalidate'], 'prefix' => 'admin'], function (){
Route::middleware(['auth', 'revalidate'])->group( function (){
  
    Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');  

    Route::get('/dashboard', 'Admin\AdminController@index')->name('home');
    
    Route::resource('usuarios', 'Admin\UsuarioController');
    
    Route::get('usuarios/rule/{id}', ['as' => 'usuarios.rule', 'uses' => 'Admin\UsuarioController@rule']);
    Route::post('usuarios/rule/{rule}', ['as' => 'usuarios.rule.store', 'uses' => 'Admin\UsuarioController@ruleStore']);
    Route::delete('usuarios/rule/{user}/{rule}', ['as' => 'usuarios.rule.destroy', 'uses' => 'Admin\UsuarioController@ruleDestroy']);
    Route::put('usuarios/changepassword/{id}',  ['as' => 'usuario.password.update', 'uses' => 'Admin\UsuarioController@changePassword']);
    Route::get('usuarios/perfil/{id}',  ['as' => 'usuario.perfil.edit', 'uses' => 'Admin\UsuarioController@editPerfil']);

    Route::resource('rules', 'Admin\RuleController');

    Route::get('rules/permission/{id}', ['as' => 'rules.permission', 'uses' => 'Admin\RuleController@permission']);
    Route::post('rules/permission/{permission}', ['as' => 'rules.permission.store', 'uses' => 'Admin\RuleController@permissionStore']);
    Route::delete('rules/permission/{rule}/{permission}', ['as' => 'rules.permission.destroy', 'uses' => 'Admin\RuleController@permissionDestroy']);


    
    Route::resource('pagina', 'Admin\PaginaController');
    
    
    Route::put('orders', ['as' => 'orders', 'uses' => 'Admin\OrderController@order']);


});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('login', 'Auth\LoginController@login')->name('admin.login');

Route::get('password/reset', function (){
    return view('auth.reset');
})->name('admin.password-reset');

Route::post('/password', array(
    'uses' => 'Auth\ResetPasswordController@postRemind',
    'as' => 'admin.password-request'
  ));

Route::get('/password/reset/{token}', array(
'uses' => 'Auth\ResetPasswordController@getReset',
'as' => 'admin.new-password-reset'
));

Route::post('/password/reset', array(
    'uses' => 'Auth\ResetPasswordController@postReset',
    'as' => 'admin.password-update'
  ));

Route::get('send-email-press', array(
    'uses' => 'Admin\JobSendEmailPressController@sendEmailPress',
    'as' => 'sendEmailPress'
  ));

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/


//SITE
Route::get('/', function() {
  return '<h1>Welcome</h1>';
});

      

    

app/Http/Controllers/Admin/UsuarioController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \App\Rule;
use \App\User;
use \App\Log;
use Illuminate\Support\Facades\Hash;

class UsuarioController extends Controller
{

    protected $model;

    public function __construct(User $model)
    {
        $this->model = $model;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => '', 'titulo' => 'Usuários'],
        ];

        $usuarios = User::with('rules')->where('role', '<>', 6)->orderBy('id', 'DESC')->paginate(30);
       
        return view('admin.usuarios.index', compact('usuarios', 'caminhos'));

    }

    public function rule($id)
    {

        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => route('usuarios.index'), 'titulo' => 'Usuários'],
            ['url' => '', 'titulo' => 'Papel'],
        ];

        $usuarios = User::find($id);
        $rules = Rule::all();
        
        return view('admin.usuarios.rule', compact('usuarios', 'rules', 'caminhos'));

    }

    //Adicionar relacionamento de rule com usuario    
    public function ruleStore(Request $request, $id)
    {
        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => route('usuarios.index'), 'titulo' => 'Usuários'],
            ['url' => '', 'titulo' => 'Papel'],
        ];

        $usuario = User::find($id);
        $dados = $request->all();
        $rule = Rule::find($dados['rule_id']);
        $usuario->adicionarRule($rule);

        return redirect()->back()->with('Permissão', 'Permissão Salva!');

    }

    //Remover relacionamento de Rule com usuario
    public function ruleDestroy($id, $rule_id)
    {
        $usuario = User::find($id);
        $rule = Rule::find($rule_id);
        $usuario->removeRule($rule);

        return redirect()->back()->with('Permissão', 'Permissão Excluída!');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => route('usuarios.index'), 'titulo' => 'Usuários'],
            ['url' => '', 'titulo' => 'Adicionar'],
        ];

        $rules = Rule::where('acesso', 'ADM')->get();

        return view('admin.usuarios.adicionar', compact('rules','caminhos'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|unique:users',
            'rule_id' => 'required',
            'password' => 'required|confirmed|min:6'
        ]);

        
        $obj = $this->model->storeAdmin($request);

        if (!$obj->save()) {
            return redirect()->back()->withErrors(['Houve um erro ao processar seu pedido, tente novamente.']);
        }


        $rule = Rule::find($request['rule_id']);
        $obj->adicionarRule($rule);

        $logs = new Log();
        $logs->insertLog('Usuário', $obj->id);

        return redirect()->route('usuarios.index')->with('status', 'Registro Salvo!');

        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        if (User::find($id)->nome == 'Admin') {
            return redirect()->route('rules.index');
        }
        
        $rules = Rule::where('acesso', 'ADM')->get();
        $usuario = User::with('rules')->find($id);
        
        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => route('usuarios.index'), 'titulo' => 'Rules'],
            ['url' => '', 'titulo' => 'Editar'],
        ];
        return view('admin.usuarios.editar', compact('usuario','rules', 'caminhos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required',
            'rule_id' => 'required',
        ]);

        $existe = User::where('email', $request['email'])->where('id', '<>', $id)->first();
        if ($existe) {
            return redirect()->back()->withErrors(['The email has already been taken.']);
        }

        if (auth()->user()->id != $id) { 
            //Verificar se o perfil do usuario é diferente de ADMIN
            if (User::with('rules')->find($id)->nome == 'Admin') {
                return redirect()->route('usuarios.index');
            }
        }

        $obj = $this->model->putAdmin($id, $request);

        if (!$obj->save()) {
            return redirect()->back()->withErrors(['Houve um erro ao processar seu pedido, tente novamente.']);
        }


        $rule = Rule::find($request['rule_id']);
        $obj->adicionarRule($rule);

        $logs = new Log();
        $logs->updateLog('Usuário', $id);
       
        
        return redirect()->route('usuarios.index')->with('status', 'Registro atualizado!');
    }

    public function changePassword(Request $request, $id)
    {
        
        $this->validate(request(), [
            'password' => 'required|min:6|confirmed'
        ]);

        $obj = User::find($id);
        $obj->password = Hash::make($request['password']);
        $obj->save();

        return back()->with('status', 'Senha atualizada!');
    }

    public function editPerfil($id)
    {
       
        $user = auth()->user();
        $usuario = User::find($user->id);
        
        
        return view('admin.usuarios.perfil', compact('usuario')); 
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Verificar se o perfil do usuario é diferente de ADMIN
        if (User::find($id)->nome == 'Admin') {
            return redirect()->route('rules.index');
        }

        User::find($id)->delete();
        
        $logs = new Log();
        $logs->deleteLog('Usuário', $id);

        return redirect()->route('usuarios.index')->with('status', 'Registro Excluído!');
    }

    
}

resources/views/admin/usuarios/adicionar.blade.php
@extends('layout.master')

@push('plugin-styles')
@endpush

@section('content')
<div class="row">
    <div class="col s12">
        @include('componentes.breadcrumbs')
    </div>

  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      
      <div class="card-body">
        
        <h4 class="card-title">Adicionar Usuários</h4>
        <p class="card-description"> </p>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
        @endif

        <div class="auto-form-wrapper">
        <form method="POST" action="{{ route('usuarios.store') }}">
            {{ csrf_field() }}
            <div class="row clearfix">  
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text"  name="name" id="name" class="form-control" placeholder="Nome"  value="{{ old('name') }}" required>
                            
                        </div>
                    </div>
                </div>  
                <div class="col-sm-6">  
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" name="email" id="email" class="form-control" placeholder="Email"  value="{{ old('email') }}" required>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                <i class="mdi mdi-check-circle-outline"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>      
            </div>
            <div class="row clearfix">  
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group">
                            <select name="rule_id" id="rule_id" class="form-control" required>
                                <option value="">Selecione um Perfil</option>
                                @if($rules)
                                    @foreach($rules as $rule)
                                        <option value="{{ $rule->id }}">{{ $rule->name }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                </div>  
                 
            </div>
            <div class="row clearfix">  
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                <i class="mdi mdi-check-circle-outline"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>  
                <div class="col-sm-6">  
                    <div class="form-group">
                        <div class="input-group">
                            <input type="password" name="password_confirmation" id="password_confirmation"  class="form-control" placeholder="Confirme o Password" required>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                <i class="mdi mdi-check-circle-outline"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>      
            </div>
            <div class="row clearfix">  
                <div class="col-sm-2">
                    <button class="btn btn-primary submit-btn btn-block">Registrar</button>
                </div>
            </div>
          
        </form>
      </div>
        
    </div>
  </div>
  
</div>
@endsection

@push('plugin-scripts')
@endpush

@push('custom-scripts')
@endpush

resources/views/admin/usuarios/editar.blade.php
@extends('layout.master')

@push('plugin-styles')
@endpush

@section('content')
<div class="row">
    <div class="col s12">
        @include('componentes.breadcrumbs')
    </div>
    
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
        
            <div class="card-body">
                @if (session('status'))
                    <div class="row clearfix">
                        <div class="col-sm-12">
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        </div>
                    </div>
                @endif

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif                
                
                <h4 class="card-title">Editar Usuário</h4>
                <p class="card-description"> </p>

                <div class="auto-form-wrapper">
                    <form action="{{ route('usuarios.update', $usuario->id)}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="row clearfix">  
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Nome" value="{{ $usuario->name }}">
                                        
                                    </div>
                                </div>
                            </div>  
                            <div class="col-sm-6">  
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="email" id="email" class="form-control" placeholder="Email" value="{{ $usuario->email }}">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                            <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>      
                        </div>
                        <div class="row clearfix">  
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <select name="rule_id" id="rule_id" class="form-control" required>
                                            @if (!isset($usuario->rules[0]->id))
                                            <option value="">Selecione um Perfil</option>
                                                @if($rules)
                                                    @foreach($rules as $rule)
                                                        <option value="{{ $rule->id }}" >{{ $rule->name }}</option>
                                                    @endforeach
                                                @endif    
                                            @else
                                                @if($rules)
                                                    @foreach($rules as $rule)
                                                        <option value="{{ $rule->id }}" {{$rule->id == @$usuario->rules[0]->id ? 'selected' : ''}}>{{ $rule->name }}</option>
                                                    @endforeach
                                                @endif
                                            @endif
                                        </select>
                                    </div>
                                </div>
                            </div>  
                            
                        </div>
                        
                        <div class="row clearfix">  
                            <div class="col-sm-2">
                                <button class="btn btn-primary submit-btn btn-block">Atualizar</button>
                            </div>
                        </div>
                    
                    </form>
                </div>
            </div>
            <div class="card-body">
                
                <h4 class="card-title">Atualizar Senha</h4>
                <p class="card-description"> </p>

                <div class="auto-form-wrapper">
                    
                    <form action="{{ route('usuario.password.update', $usuario->id)}}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="row clearfix">  
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="password" class="form-control" placeholder="Password" name="password" value="">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                            <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>  
                            <div class="col-sm-6">  
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="password" class="form-control" placeholder="Confirme o Password" name="password_confirmation" value="">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                            <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>      
                        </div>
                        <div class="row clearfix">  
                            <div class="col-sm-2">
                                <button class="btn btn-primary submit-btn btn-block">Atualizar</button>
                            </div>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('plugin-scripts')
@endpush

@push('custom-scripts')
@endpush

resources/views/admin/usuarios/index.blade.php
@extends('layout.master')

@push('plugin-styles')
@endpush

@section('content')
<div class="row">
  

  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      
      <div class="card-body">

        @if (session('status'))
            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                </div>
            </div>
        @endif    
             
        @can('usuario-create')  
        <div>
          <a href="{{ route('usuarios.create') }}" class="btn btn-primary btn-fw btn-add"><i class="mdi mdi-plus"></i>Adicionar</a>
        </div>
        @endcan
        <h4 class="card-title">Usuários</h4>
        <p class="card-description"> </p>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th> Id </th>
                <th> Nome </th>
                <th> Email </th>
                <th> Perfil </th>
                <th> Ações </th>
              </tr>
            </thead>
            <tbody>
            @forelse($usuarios as $usuario)
              <tr>
                <td> {{ $usuario->id }} </td>
                <td> {{ $usuario->name }} </td>
                <td>
                  {{ $usuario->email }}
                </td>
                <td> {{ @$usuario->rules[0]->name }} </td>
                <td> 
                    <form action="{{route('usuarios.destroy', $usuario->id)}}" method="post">
                        @can('usuario-edit')  
                            <a title="Editar" class="btn btn-icons btn-inverse-warning" href="{{ route('usuarios.edit', $usuario->id) }}"><i class="mdi mdi-grease-pencil"></i></a>
                        @endcan  
                        @can('usuario-delete')  
                            {{method_field('DELETE')}}
                            {{csrf_field()}}
                            <button title="Deletar" class="btn btn-icons btn-inverse-danger"><i class="mdi mdi-delete"></i></button>   
                        @endcan
                    </form>     
                </td>
              </tr>
              @empty
            </tbody>
              <tr>
                <td colspan="6">Nenhum registro encontrado.</td>
              </tr>
            @endforelse
          </table>
          {{ $usuarios->appends(request()->input())->links() }}
        </div>
      </div>
    </div>
  </div>
  
</div>
@endsection

@push('plugin-scripts')
@endpush

@push('custom-scripts')
@endpush

resources/views/admin/usuarios/perfil.blade.php
@extends('layout.master')

@push('plugin-styles')
@endpush

@section('content')
<div class="row">
    <div class="col s12">
        @include('componentes.breadcrumbs')
    </div>
    
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
        
            <div class="card-body">
                @if (session('status'))
                    <div class="row clearfix">
                        <div class="col-sm-12">
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        </div>
                    </div>
                @endif

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif      
                
                <h4 class="card-title">Atualizar Senha</h4>
                <p class="card-description"> </p>

                <div class="auto-form-wrapper">
                    
                    <form action="{{ route('usuario.password.update', $usuario->id)}}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="row clearfix">  
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="password" class="form-control" placeholder="Password" name="password" value="">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                            <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>  
                            <div class="col-sm-6">  
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="password" class="form-control" placeholder="Confirme o Password" name="password_confirmation" value="">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                            <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>      
                        </div>
                        <div class="row clearfix">  
                            <div class="col-sm-2">
                                <button class="btn btn-primary submit-btn btn-block">Atualizar</button>
                            </div>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('plugin-scripts')
@endpush

@push('custom-scripts')
@endpush

resources/views/admin/usuarios/rule.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="center">Lista de Papéis para {{$usuarios->name}}</h2>

        @include('admin.breadcrumb')

        <div class="row">
            <form action="{{route('usuarios.rule.store', $usuarios->id)}}" method="post">
                {{ csrf_field() }}
                <div class="input-field">
                    <select name="rule_id" id="rule_id" style="display:block">
                        @foreach($rules as $valor)
                            <option value="{{$valor->id}}">{{$valor->name}}</option>
                        @endforeach
                    </select>
                </div>
                <button class="btn blue">Adicionar</button>
            </form>
        </div>

    
        <div class="row">
            <table>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Ação</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($usuarios->rules as $rule)
                    <tr>
                        <td>{{$rule->name}}</td>
                        <td>{{$rule->description}}</td>
                        <td>
                            <form action="{{route('usuarios.rule.destroy', [$usuarios->id, $rule->id])}}" method="post">
                                {{ method_field('DELETE')}}
                                {{csrf_field()}}
                                <button title="Deletar" class="btn red" href="#"><i class="material-icons">delete</i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection    