routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
*/


use Illuminate\Support\Facades\Auth;


  
// Route::group(['middleware' => ['auth', 'revalidate'], 'prefix' => 'admin'], function (){
Route::middleware(['auth', 'revalidate'])->group( function (){
  
    Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');  

    Route::get('/dashboard', 'Admin\AdminController@index')->name('home');
    
    Route::resource('usuarios', 'Admin\UsuarioController');
    
    Route::get('usuarios/rule/{id}', ['as' => 'usuarios.rule', 'uses' => 'Admin\UsuarioController@rule']);
    Route::post('usuarios/rule/{rule}', ['as' => 'usuarios.rule.store', 'uses' => 'Admin\UsuarioController@ruleStore']);
    Route::delete('usuarios/rule/{user}/{rule}', ['as' => 'usuarios.rule.destroy', 'uses' => 'Admin\UsuarioController@ruleDestroy']);
    Route::put('usuarios/changepassword/{id}',  ['as' => 'usuario.password.update', 'uses' => 'Admin\UsuarioController@changePassword']);
    Route::get('usuarios/perfil/{id}',  ['as' => 'usuario.perfil.edit', 'uses' => 'Admin\UsuarioController@editPerfil']);

    Route::resource('rules', 'Admin\RuleController');

    Route::get('rules/permission/{id}', ['as' => 'rules.permission', 'uses' => 'Admin\RuleController@permission']);
    Route::post('rules/permission/{permission}', ['as' => 'rules.permission.store', 'uses' => 'Admin\RuleController@permissionStore']);
    Route::delete('rules/permission/{rule}/{permission}', ['as' => 'rules.permission.destroy', 'uses' => 'Admin\RuleController@permissionDestroy']);


    
    Route::resource('pagina', 'Admin\PaginaController');
    
    
    Route::put('orders', ['as' => 'orders', 'uses' => 'Admin\OrderController@order']);


});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('login', 'Auth\LoginController@login')->name('admin.login');

Route::get('password/reset', function (){
    return view('auth.reset');
})->name('admin.password-reset');

Route::post('/password', array(
    'uses' => 'Auth\ResetPasswordController@postRemind',
    'as' => 'admin.password-request'
  ));

Route::get('/password/reset/{token}', array(
'uses' => 'Auth\ResetPasswordController@getReset',
'as' => 'admin.new-password-reset'
));

Route::post('/password/reset', array(
    'uses' => 'Auth\ResetPasswordController@postReset',
    'as' => 'admin.password-update'
  ));

Route::get('send-email-press', array(
    'uses' => 'Admin\JobSendEmailPressController@sendEmailPress',
    'as' => 'sendEmailPress'
  ));

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/


//SITE
Route::get('/', function() {
  return '<h1>Welcome</h1>';
});

      

    

app/Http/Controllers/Admin/PaginaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Model\Pagina;
use App\Log;

class PaginaController extends Controller
{


    protected $model;

    public function __construct(Pagina $model)
    {
        $this->model = $model;
    }


    public function index()
    {
        if (Gate::denies('paginas-view')){
            abort(403, "Não autorizado");
        }

        $objs = Pagina::orderBy('id', 'DESC')->paginate(30);
        //dd($objs);
        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => '', 'titulo' => 'Páginas'],
        ];
        return view('admin.institucional.pagina.index', compact('objs', 'caminhos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('paginas-create')){
            abort(403, "Não autorizado");
        }        

        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => route('pagina.index'), 'titulo' => 'Páginas'],
            ['url' => '', 'titulo' => 'Adicionar'],
        ];
        return view('admin.institucional.pagina.adicionar', compact('caminhos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Gate::denies('paginas-create')){
            abort(403, "Não autorizado");
        }        

        $request->validate([
            'title' => 'required|max:255',
        ],
        [
            'title.required' => 'Título precisa ser informado',
        ]);

        $obj = $this->model->store($request);

        if (!$obj->save()) {
            return redirect()->back()->withErrors(['Houve um erro ao processar seu pedido, tente novamente.']);
        }

        $logs = new Log();
        $logs->insertLog('Página', $obj->id);         
        
        return redirect()->route('pagina.index')->with('status', 'Registro Salvo!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('paginas-edit')){
            abort(403, "Não autorizado");
        }                

        $obj = Pagina::with('featured_img', 'featured_img_mobile')->find($id);
        //dd($obj);
        
        $caminhos = [
            ['url' => '/admin', 'titulo' => 'Admin'],
            ['url' => route('pagina.index'), 'titulo' => 'Paginas'],
            ['url' => '', 'titulo' => 'Editar'],
        ];
        return view('admin.institucional.pagina.editar', compact('obj','caminhos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Gate::denies('paginas-edit')){
            abort(403, "Não autorizado");
        }        

        $request->validate([
            'title' => 'required|max:255',
        ],
        [
            'title.required' => 'Título precisa ser informado',
        ]);

        $obj = $this->model->put($id, $request);

        
       
        $obj->save();
        
        $logs = new Log();
        $logs->updateLog('Página', $id);         

        return redirect()->route('pagina.edit', $id )->with('status', 'Registro Atualizado!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('paginas-delete')){
            abort(403, "Não autorizado");
        }                
        
        Pagina::find($id)->delete();
        
        $logs = new Log();
        $logs->deleteLog('Página', $id); 

        return redirect()->route('pagina.index')->with('status', 'Registro Excluído!');
    }

}

resources/views/admin/institucional/pagina/adicionar.blade.php
@extends('layout.master')

@push('plugin-styles')
@endpush

@section('content')
<div class="row">
    <div class="col s12">
        @include('componentes.breadcrumbs')
    </div>

    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">

            <div class="card-body">

                <h4 class="card-title">Adicionar Páginas </h4>
                <p class="card-description"> </p>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif

                <div class="auto-form-wrapper">
                    <form action="{{ route('pagina.store')}}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        
                        <input type="hidden" name="featured_img_id" id="featured_img_id" value="{{old('featured_img_id')}}">
                        <input type="hidden" name="featured_img_mobile_id" id="featured_img_mobile_id" value="{{ old('featured_img_mobile_id')}}">

                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="title" id="title" class="validate form-control"
                                            value="{{ old('title')}}"
                                            Placeholder="Título da Página" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        

                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <p>Imagem Banner</p>
                                    <div class="input-group">
                                        <input type="file" name="image" id="image" data-model="pagina" data-inputid="featured_img_id" class="form-control image">
                                    </div>
                                    <br />
                                    <p><img src="{{ isset($obj->featured_img->id) ? $actual_link.$obj->featured_img->directory.$obj->featured_img->url : '' }}" width="150" class="fl-donwload featured_img_id {{ isset($obj->featured_img->id) ? : 'hide'}} "></p>
                                </div>
                            </div>
                        </div>
            
            
                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <p>Imagem Mobile</p>
                                    <div class="input-group">
                                        <input type="file" name="image_mobile" id="image_mobile" data-model="pagina" data-inputid="featured_img_mobile_id" class="form-control image">
                                    </div>
                                    <br />
                                    <p><img src="{{ isset($obj->featured_img_mobile->id) ? $actual_link. $obj->featured_img_mobile->directory.$obj->featured_img_mobile->url : '' }}" width="150" class="fl-donwload featured_img_mobile_id {{ isset($obj->featured_img_mobile->id) ? : 'hide'}}"></p>
                                </div>
                            </div>
                        </div>
            

                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="title_banner" id="title_banner" class="validate form-control"
                                            value="{{old('title_banner')}}"
                                            Placeholder="Título Banner" >
                                    </div>
                                </div>
                            </div>
                        </div>

                        

                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <p>Descrição</p>
                                    <div class="input-group">
                                        <textarea name="description" id="description" class="description">{{ old('description')}}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <p>Descrição EN</p>
                                    <div class="input-group">
                                        <textarea name="description_en" id="description_en" class="description">{{ old('description_en')}}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="date" name="date_published" id="date_published" class="validate form-control "
                                            value="{{ old('date_published')}}"
                                            Placeholder="Data de Publicação" >
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-field">
                                        <select name="status" id="status" class="form-control c-tipo__blog" required>
                                            <option value="">Status</option>
                                            <option value="1" {{ (old('status') == '1') ? 'selected' :  ''}}>Ativo</option>
                                            <option value="0" {{ (old('status') == '0') ? 'selected' :  ''}}>Inativo</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            {{-- <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="hour_published" id="hour_published" class="validate form-control"
                                            value="{{ old('hour_published')}}"
                                            Placeholder="Hora de Publicação" >
                                    </div>
                                </div>
                            </div> --}}
                        </div>   

                        

                                
                        <h5 class="title_section">CTA para Contato</h5>
                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="cta_text" id="cta_text" class="validate form-control"
                                            value="{{old('cta_text')}}"
                                            Placeholder="Cta Texto" >
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="cta_button" id="cta_button" class="validate form-control"
                                            value="{{old('cta_button')}}"
                                            Placeholder="Texto botão" >
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="cta_btcolor" id="cta_btcolor" class="validate form-control"
                                            value="{{old('cta_btcolor')}}"
                                            Placeholder="Cor do botão" >
                                    </div>
                                </div>
                            </div>
                        </div>   
                        
                        <div class="row clearfix">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="cta_link" id="cta_link" class="validate form-control"
                                            value="{{old('cta_link')}}"
                                            Placeholder="Link Cta" >
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="input-group">
                                        <select name="target" id="target" class="form-control" >
                                            <option value="">Selecione um Target</option>
                                            <option value="0" {{ (old('cta_btcolor') == 0) ? 'selected' : '' }}>Abrir na mesma Aba</option>
                                            <option value="1" {{ (old('cta_btcolor') == 1) ? 'selected' : '' }}>Abrir em nova Aba</option>
                                        </select>
                                    </div>
                                </div>
                            </div>   
                        </div>

                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-check form-check-flat">
                                    <label class="form-check-label">
                                      <input type="checkbox" class="form-check-input" name="bt_proposta" value="1" {{ (old('bt_proposta') == 1) ? 'checked' : '' }}>Exibir botão "Solicitar Proposta" 
                                    </label>
                                </div>
                            </div>  
                        </div>

                        <h5 class="title_section">Metas Tag</h5>
                        <div class="row clearfix">  
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text"  name="title_html" id="title_html" class="form-control" placeholder="Título Meta"  value="{{ old('title_html') }}" >
                                    </div>
                                </div>
                            </div>  
                        </div>
                        <div class="row clearfix">  
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text"  name="description_html" id="description_html" class="form-control" placeholder="Descrição Meta"  value="{{  old('description_html') }}" >
                                    </div>
                                </div>
                            </div>  
                        </div>

                        
                        <div class="row clearfix">
                            <div class="col-sm-3">
                                <button class="btn btn-primary submit-btn btn-block">Registrar</button>
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>

    </div>
</div>
@endsection

@push('plugin-scripts')
@endpush

@push('custom-scripts')
@endpush

resources/views/admin/institucional/pagina/index.blade.php
@extends('layout.master')

@push('plugin-styles')
@endpush

@section('content')
<div class="row">
  

  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      
      <div class="card-body">


        @if (session('status'))
            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                </div>
            </div>
        @endif  
             
        @can('paginas-create')
        <div>
          <a href="{{ route('pagina.create') }}" class="btn btn-primary btn-fw btn-add"><i class="mdi mdi-plus"></i>Adicionar</a>
        </div>
        @endcan
        <h4 class="card-title">Páginas</h4>
        <p class="card-description"> Listagem de páginas </p>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th> Id </th>
                <th> Título </th>
                <th> slug </th>
                <th> Ações </th>
              </tr>
            </thead>
            <tbody>
            @forelse($objs as $obj)
              <tr>
                <td> {{ $obj->id }} </td>
                <td> {{$obj->title}}</td>
                <td> {{$obj->slug}}</td>
               
                <td> 
                    <form action="{{route('pagina.destroy', $obj->id)}}" method="post">
                        @can('paginas-edit')
                            <a title="Editar" class="btn btn-icons btn-inverse-warning" href="{{route('pagina.edit', $obj->id)}}"><i class="mdi mdi-grease-pencil"></i></a>
                        @endcan
                        @can('paginas-delete')
                            {{method_field('DELETE')}}
                            {{csrf_field()}}
                            <button title="Deletar" class="btn btn-icons btn-inverse-danger"><i class="mdi mdi-delete"></i></button>   
                        @endcan
                        
                    </form>     
                </td>
              </tr>
              @empty
            </tbody>
              <tr>
                <td colspan="6">Nenhum registro encontrado.</td>
              </tr>
            @endforelse
          </table>
          {{ $objs->appends(request()->input())->links() }}
        </div>
      </div>
    </div>
  </div>
  
</div>
@endsection

@push('plugin-scripts')
@endpush

@push('custom-scripts')
@endpush

        